{
 "title": "Node Unit / Deployment Resources",
 "tags": [ "node-unit" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node_unit_name",
    "query": {
     "query": "label_values(node_unit_deployment_info, node_unit_name)"
    }
   },
   {
    "name": "package_name",
    "query": {
     "query": "label_values(node_unit_deployment_info, package_name)"
    }
   },
   {
    "name": "package_version",
    "query": {
     "query": "label_values(node_unit_deployment_info, package_version)"
    }
   },
   {
    "name": "deployment_id",
    "query": {
     "query": "label_values(node_unit_deployment_info, deployment_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Rate (Total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nodejs_process_resource_usage{type=\"userCPUTime\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU Rate by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment_id, package_name, package_version, node_unit_name) (rate(nodejs_process_resource_usage{type=\"userCPUTime\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"}[5m]))",
     "legendFormat": "{{deployment_id}} - {{package_name}}"
    }
   ]
  },
  {
   "title": "CPU Top 10 (Current)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (deployment_id, package_name, package_version, node_unit_name) (rate(nodejs_process_resource_usage{type=\"userCPUTime\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Peak 1h (Max)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, max_over_time((sum by (deployment_id, package_name, package_version, node_unit_name) (rate(nodejs_process_resource_usage{type=\"userCPUTime\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"}[5m])))[1h:]))"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory RSS (Total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_process_resource_usage{type=\"rss\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory RSS by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment_id, package_name, package_version, node_unit_name) (nodejs_process_resource_usage{type=\"rss\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"})",
     "legendFormat": "{{deployment_id}}"
    }
   ]
  },
  {
   "title": "Memory Top 10 (Current)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (deployment_id, package_name, package_version, node_unit_name) (nodejs_process_resource_usage{type=\"rss\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"}))"
    }
   ]
  },
  {
   "title": "Memory Peak 1h (Max)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, max_over_time((sum by (deployment_id, package_name, package_version, node_unit_name) (nodejs_process_resource_usage{type=\"rss\"} * on(terminal_id) group_left(deployment_id, package_name, package_version, node_unit_name, node_unit_address) node_unit_deployment_info{node_unit_name=~\"$node_unit_name\",package_name=~\"$package_name\",package_version=~\"$package_version\",deployment_id=~\"$deployment_id\"}))[1h:]))"
    }
   ]
  }
 ]
}