blank_issues_enabled: false

contact_links:
  - name: Ask a question
    url: https://github.com/No-Trade-No-Life/Yuan/discussions/new
    about: Ask a question or start a discussion
  - name: Chat on Discord
    url: https://discord.gg/fj6j3Qmd
    about: Maybe chatting with the community can help
