import { hostname } from 'os';
import { DEFAULT_CONTEXT_NAME } from '../constants';
import { stringify } from 'yaml';

export interface DefaultConfigOptions {
  hostUrl?: string;
  terminalId?: string;
}

export const generateDefaultToml = (options: DefaultConfigOptions = {}): string => {
  const host = options.hostUrl ?? 'wss://example-host/ws';
  const terminalId = options.terminalId ?? `Yuanctl/${hostname()}`;
  return [
    '# Generated by yuanctl config-init',
    `current_context = "${DEFAULT_CONTEXT_NAME}"`,
    '',
    `[hosts.${DEFAULT_CONTEXT_NAME}]`,
    `host_url = "${host}"`,
    'tls_verify = true',
    'connect_timeout_ms = 5000',
    'reconnect_delay_ms = 2000',
    `terminal_id = "${terminalId}"`,
    '',
    `[contexts.${DEFAULT_CONTEXT_NAME}]`,
    `host = "${DEFAULT_CONTEXT_NAME}"`,
    `terminal_id = "${terminalId}"`,
    '',
  ].join('\n');
};

export const formatConfigAsYaml = (data: Record<string, unknown>): string =>
  stringify(data, { aliasDuplicateObjects: false });
